# Generated by Django 5.1.2 on 2024-11-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_author_book_writer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='star',
            field=models.IntegerField(null=True),
        ),
    ]
