# Generated by Django 4.2.16 on 2024-11-10 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_answer_user_alter_question_user_and_more'),
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
