# Generated by Django 5.1.2 on 2024-11-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default='default_nickname', max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
