# Generated by Django 4.2.11 on 2024-11-11 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_answer_user_alter_question_user_and_more'),
        ('reading_log', '0003_alter_userreadinglog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreadinglog',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
